use std::fmt::Display;

/// A currency from the ISO 4217 registry.
///
/// Curated currencies are compiled in as `const fn` constructors
/// (e.g. `Currency::usd()`), generated by `build.rs` and pulled in via the
/// `include!` at the bottom of this file — same mechanism as `Mic`.
///
/// Every field is a string except `precision`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Currency {
    /// Human-readable currency name, e.g. "US Dollar".
    name: &'static str,
    /// 3-letter alphabetic code, e.g. "USD".
    alphabetic_code: &'static str,
    /// 3-digit numeric code, zero-padded, e.g. "840".
    numeric_code: &'static str,
    /// Minor-unit precision: digits after the decimal separator (0 if none).
    precision: u8,
}

impl Currency {
    pub const fn new(
        name: &'static str,
        alphabetic_code: &'static str,
        numeric_code: &'static str,
        precision: u8,
    ) -> Self {
        Currency {
            name,
            alphabetic_code,
            numeric_code,
            precision,
        }
    }

    pub const fn name(&self) -> &'static str {
        self.name
    }

    pub const fn alphabetic_code(&self) -> &'static str {
        self.alphabetic_code
    }

    pub const fn numeric_code(&self) -> &'static str {
        self.numeric_code
    }

    pub const fn precision(&self) -> u8 {
        self.precision
    }
}

impl Display for Currency {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.alphabetic_code)
    }
}

// Curated `pub const fn` constructors, generated by build.rs into an
// `impl Currency { ... }` block. Keep in sync with the emission in build.rs.
include!(concat!(env!("OUT_DIR"), "/currency_generated.rs"));
