[package]
name = "tradeprim"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", optional = true, default-features = false, features = ["derive"] }


[dev-dependencies]
proptest = "1.11.0"
serde_json = "1.0"

[build-dependencies]
csv = { version = "1" }

[features]
serde = ["dep:serde"]
