use csv::ReaderBuilder;
use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

const CSV_PATH: &str = "./assets/ISO10383_MIC.csv";

/// MICs always compiled in. With `mic-full`, this filter is bypassed.
const CURATED: &[&[u8; 4]] = &[
    b"XNAS", b"XNYS", b"ARCX", b"BATS", b"IEXG", b"XASE", b"XCME", b"XCBT", b"XCBO", b"XNYM",
    b"XCEC", b"XLON", b"XPAR", b"XAMS", b"XBRU", b"XLIS", b"XETR", b"XFRA", b"XMIL", b"XSWX",
    b"XTKS", b"XHKG", b"XSHG", b"XSHE", b"XKRX", b"XASX", b"XBOM", b"XNSE", b"XTSE", b"XTSX",
    b"XEUR", b"XLBM", b"XSGE",
];

fn main() {
    println!("cargo::rerun-if-changed=build.rs");
    println!("cargo::rerun-if-changed={}", CSV_PATH);

    let full = env::var_os("CARGO_FEATURE_MIC_FULL").is_some();

    let mut reader = ReaderBuilder::new()
        .double_quote(true)
        .from_path(CSV_PATH)
        .expect("build.rs: failed to read ISO10383_MIC.csv");

    let mut arms = String::new();
    let mut ctors = String::new();
    let mut count = 0usize;

    for record in reader.records() {
        let row = record.expect("build.rs: malformed CSV row");

        let code = field(&row, 0);
        if code.len() != 4 {
            continue;
        }
        let code_bytes: [u8; 4] = code.as_bytes().try_into().unwrap();
        let is_curated = CURATED.iter().any(|c| **c == code_bytes);

        if !full && !is_curated {
            continue;
        }

        let expr = mic_expr(&row, &code_bytes);

        writeln!(arms, "        \"{code}\" => Some({expr}),").unwrap();

        if is_curated {
            let fn_name = code.to_ascii_lowercase();
            let market_name = field(&row, 3);
            let mic_type = field(&row, 2);
            let operating = field(&row, 1);
            let kind = match mic_type {
                "OPRT" => "operating".to_string(),
                "SGMT" => format!("segment of `{operating}`"),
                other => panic!("unknown MIC type: {other:?}"),
            };
            writeln!(
                ctors,
                "    /// {market_name} (`{code}`, {kind}).\n    pub const fn {fn_name}() -> Self {{ {expr} }}",
            )
            .unwrap();
        }

        count += 1;
    }

    let body = format!(
        r#"// @generated by build.rs from {csv} ({count} entries)

/// Returns the registry record for a MIC code, if known to this build.
///
/// By default only common MICs are compiled in (~30 entries).
/// Enable the `mic-full` feature for the full ISO 10383 registry.
///
/// Returns `None` for any code that isn't an exact 4-character match
/// against a known MIC.
///
/// # Examples
///
/// ```
/// use instrid::mic::mic_by_code;
///
/// assert!(mic_by_code("XNAS").is_some());
/// assert!(mic_by_code("ZZZZ").is_none());
/// assert!(mic_by_code("XNA").is_none());   // wrong length
/// ```
pub fn mic_by_code(code: &str) -> Option<Mic> {{
    match code {{
{arms}        _ => None,
    }}
}}

/// Curated MIC constructors. Always compiled in regardless of features.
impl Mic {{
{ctors}}}
"#,
        csv = CSV_PATH,
    );

    let out_dir = env::var_os("OUT_DIR").expect("OUT_DIR not set");
    let dest = Path::new(&out_dir).join("mic_generated.rs");
    fs::write(&dest, body).expect("build.rs: failed to write mic_generated.rs");
}

fn field<'a>(row: &'a csv::StringRecord, idx: usize) -> &'a str {
    row.get(idx).unwrap_or("").trim()
}

fn mic_expr(row: &csv::StringRecord, code: &[u8; 4]) -> String {
    let code_str = std::str::from_utf8(code).unwrap();
    format!(
        "Mic::new(*b\"{code}\", {operating}, {market_name}, {mic_type}, \
         {legal_entity}, {lei}, {category}, {acronym}, {country}, {city}, \
         {website}, {status}, {creation}, {last_update}, {last_validation}, \
         {expiry}, {comments})",
        code = code_str,
        operating = code4_lit(field(row, 1)),
        mic_type = mic_type_lit(field(row, 2)),
        market_name = str_lit(field(row, 3)),
        legal_entity = opt_str_lit(field(row, 4)),
        lei = opt_lei_lit(field(row, 5)),
        category = category_lit(field(row, 6)),
        acronym = opt_str_lit(field(row, 7)),
        country = code2_lit(field(row, 8)),
        city = str_lit(field(row, 9)),
        website = opt_str_lit(field(row, 10)),
        status = status_lit(field(row, 11)),
        creation = date_lit(field(row, 12)).expect("missing creation date"),
        last_update = date_lit(field(row, 13)).expect("missing last_update date"),
        last_validation = opt_date_lit(field(row, 14)),
        expiry = opt_date_lit(field(row, 15)),
        comments = opt_str_lit(field(row, 16)),
    )
}

fn str_lit(s: &str) -> String {
    let escaped = s.replace('\\', "\\\\").replace('"', "\\\"");
    format!("\"{escaped}\"")
}

fn opt_str_lit(s: &str) -> String {
    if s.is_empty() {
        "None".into()
    } else {
        format!("Some({})", str_lit(s))
    }
}

fn code4_lit(s: &str) -> String {
    assert_eq!(s.len(), 4, "expected 4-char code, got {s:?}");
    format!("*b\"{s}\"")
}

fn code2_lit(s: &str) -> String {
    assert_eq!(s.len(), 2, "expected 2-char country code, got {s:?}");
    format!("*b\"{s}\"")
}

fn opt_lei_lit(s: &str) -> String {
    if s.is_empty() {
        return "None".into();
    }
    assert_eq!(s.len(), 20, "expected 20-char LEI, got {s:?}");
    format!("Some(*b\"{s}\")")
}

fn mic_type_lit(s: &str) -> &'static str {
    match s {
        "OPRT" => "MicType::Operating",
        "SGMT" => "MicType::Segment",
        other => panic!("unknown MIC type: {other:?}"),
    }
}

fn status_lit(s: &str) -> &'static str {
    match s {
        "ACTIVE" => "MicStatus::Active",
        "EXPIRED" => "MicStatus::Expired",
        "UPDATED" => "MicStatus::Updated",
        other => panic!("unknown MIC status: {other:?}"),
    }
}

fn category_lit(s: &str) -> String {
    let variant = match s {
        "APPA" => "Appa",
        "ARMS" => "Arms",
        "CASP" => "Casp",
        "CTPS" => "Ctps",
        "DCMS" => "Dcms",
        "IDQS" => "Idqs",
        "MLTF" => "Mltf",
        "NSPD" => "Nspd",
        "OTFS" => "Otfs",
        "OTHR" => "Othr",
        "RMKT" => "Rmkt",
        "RMOS" => "Rmos",
        "SEFS" => "Sefs",
        "SINT" => "Sint",
        "TRFS" => "Trfs",
        other if other.len() == 4 => {
            return format!("MarketCategoryCode::Unknown(*b\"{other}\")");
        }
        other => panic!("invalid market category code: {other:?}"),
    };
    format!("MarketCategoryCode::{variant}")
}

fn date_lit(s: &str) -> Option<String> {
    if s.is_empty() {
        return None;
    }
    let bytes = s.as_bytes();
    assert_eq!(bytes.len(), 8, "expected YYYYMMDD, got {s:?}");
    let year: u16 = s[0..4].parse().expect("invalid year");
    let month: u8 = s[4..6].parse().expect("invalid month");
    let day: u8 = s[6..8].parse().expect("invalid day");
    Some(format!("Date::new({year}, {month}, {day})"))
}

fn opt_date_lit(s: &str) -> String {
    match date_lit(s) {
        Some(d) => format!("Some({d})"),
        None => "None".into(),
    }
}
