[package]
name = "instrid"
version = "0.1.0"
edition = "2024"
description = "Financial instrument identification types"
license = "MIT OR Apache-2.0"

[dependencies]
rust_decimal = "1.42.0"
serde = { version = "1", optional = true, features = ["derive"] }
tradeprim = { path = "../tradeprim" }

[dev-dependencies]
rust_decimal_macros = "1.40.0"
serde_json = { version = "1" }

[build-dependencies]
csv = { version = "1" }

[features]
default = []
mic-full = []
serde = ["dep:serde", "rust_decimal/serde", "tradeprim/serde"]
